---
- hosts: coder_workspace_vm
  gather_facts: False
  vars:
    - php_versions: []
    - composer_versions: []
    - mysql_versions: []
    - postgresql_versions: []
    - mailhog_versions: []
  pre_tasks:
    - name: 'Ensure python'
      raw: "sh -c 'which python3 > /dev/null || (apt -yqq update && apt install -yqq python3)'"
      args:
        warn: false
      tags: 
        - always

        #- name: 'Installing facts.d'
        #copy:
        #src: facts.d
        #dest:  /etc/ansible/
        #owner: root
        #mode: u=rwx,g=rx,o=rx
        #tags: 
        #- always

    - name: Gathering facts
      setup:
      tags: 
        - always
    
    - name: Homebrew prefix
      ansible.builtin.set_fact:
        homebrew_prefix: "/home/linuxbrew/.linuxbrew"
      when: "ansible_system == 'Linux'"
      tags:
        - always

    - name: Honebrew prefix
      ansible.builtin.set_fact:
        homebrew_prefix: "/usr/local"
      when: "ansible_system == 'Darwin' and ansible_architecture == 'x86_64'"
      tags:
        - always

    - name: Honebrew prefix
      ansible.builtin.set_fact:
        homebrew_prefix: "/opt/prefix"
      when: "ansible_system == 'Darwin' and ansible_architecture == 'arm64'"
      tags:
        - always

    - name: "Stopping digitalspace-supervisor"
      shell: '[ -e {{ homebrew_prefix }}/bin/digitalspace-supervisor-stop ] && {{ homebrew_prefix }}/bin/digitalspace-supervisor-stop || /bin/true || /usr/bin/true'
      become: true
      become_user: "root"
      tags: 
        - always

  roles:
    # - name: system-print-info
    #   tags:
    #     - debug_info

    - role: roles/system-base
      when: "ansible_system == 'Linux'"
      tags: 
        - base-system

    - role: roles/user-developer
      when: "ansible_system == 'Linux'" 
      tags: 
        - base-system

    - role: roles/zsh
      tags: 
        - zsh

    - role: roles/system-homebrew
      when: developer_username is defined and ansible_system == 'Linux'
      tags:
        - base-system

    - role: roles/supervisor
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined
      tags:
        - php70
        - php71
        - php72
        - php73
        - php74
        - php80
        - php81
        - php82
        - php83
        - mailhog
        - postgresql15
        - mysql80

    - role: roles/nginx
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined
      tags:
        - php70
        - php71
        - php72
        - php73
        - php74
        - php80
        - php81
        - php82
        - php83

    - role: roles/php70
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined
      tags:
        - php70

    - role: roles/php71
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined
      tags:
        - php71
    
    - role: roles/php72
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined
      tags:
        - php72
    
    - role: roles/php73
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined
      tags:
        - php73

    - role: roles/php74
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined
      tags:
        - php74

    - role: roles/php80
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined
      tags:
        - php80

    - role: roles/php81
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined
      tags:
        - php81

    - role: roles/php82
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined
      tags:
        - php82

    - role: roles/php83
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined
      tags:
        - php83
    
    - role: roles/phpNone
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined
      tags:
        - phpNone

    - role: roles/mysql80
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined
    
    - role: roles/postgresql15
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined

    - role: roles/composer
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined
    
    - role: roles/mailhog
      become: yes
      become_user: "{{ developer_username }}"
      when: developer_username is defined

  post_tasks:
    - shell: "echo $({{ homebrew_prefix }}/bin/brew list | grep 'php[0-9]\\+' | grep -v \"{{ php_versions | join('\\|') }}\" || /bin/true || /usr/bin/true)"
      register: brew_list
      become: yes
      become_user: "{{ developer_username }}"
      tags:
        - always
    
    - name: "Remove another php versions"
      shell: "{{ homebrew_prefix }}/bin/brew uninstall --ignore-dependencies {{ brew_list.stdout }}"
      become: yes
      become_user: "{{ developer_username }}"
      when: brew_list.stdout != ""
      tags:
        - always
    
    - name: "Stat digitalspace-supervisor.d dir"
      stat:
        path: "{{ homebrew_prefix }}/etc/digitalspace-supervisor.d"
      register: stat_etc_digitalspace_supervisor_d
      become: true
      tags:
        - always

    - name: "Remove another php versions from supervisor"
      shell: 
        cmd: "ls | grep 'php[0-9]\\+' | grep -v \"{{ php_versions | join('\\|') }}\" | xargs --no-run-if-empty -I{} rm {}"
        chdir: "{{ homebrew_prefix }}/etc/digitalspace-supervisor.d"
      become: yes
      become_user: "{{ developer_username }}"
      when: stat_etc_digitalspace_supervisor_d.stat.exists 
      tags:
        - always

    - name: "Starting digitalspace-supervisor"
      shell: '[ -e {{ homebrew_prefix }}/bin/digitalspace-supervisor-start ] && {{ homebrew_prefix }}/.linuxbrew/bin/digitalspace-supervisor-start || /bin/true || /usr/bin/true'
      become: true
      become_user: "root"
      tags:
        - always

    - name: "Changing default shell to zsh "
      shell: 'chsh -s $(which zsh)'
      become: true
      become_user: "root"
      when: "ansible_system == 'Linux'"
      tags:
        - zsh

    - name: "Changing default shell to zsh for {{ developer_username }}"
      shell: 'chsh -s $(which zsh) {{ developer_username }}'
      become: true
      become_user: "root"
      tags:
        - zsh
      when: developer_username is defined
