---
- name: Ensure that taps are tapped.
  homebrew_tap: 
    tap: "{{ item }}"
    state: "present"
    path: "/home/linuxbrew/.linuxbrew/bin"
  with_items:
  - "digitalspacestdio/ngdev"

- name: "Ensure mysql84"
  homebrew:
    name: "digitalspace-mysql84"
    state: latest
  tags:
    - mysql84

- name: "Adding 'mysql84' to 'mysql_versions' array"
  set_fact:
    mysql_versions: "{{ mysql_versions + [ 'mysql84' ] }}"
  tags:
    - mysql84

- name: "Remove mysql84"
  homebrew:
    name: "digitalspace-mysql84"
    state: absent
  when: "mysql_versions is not defined or mysql_versions | length < 1"
  tags:
    - mysqlNone

- name: "Remove mysql84 from supervisor"
  shell: 
    cmd: "ls | grep 'mysql84' | xargs --no-run-if-empty -I{} rm {}"
    chdir: "{{ homebrew_prefix }}/etc/digitalspace-supervisor.d"
  when: "mysql_versions is not defined or mysql_versions | length < 1"
  tags:
    - mysqlNone