---
- shell: "getent passwd '{{ developer_uid }}' | cut -d: -f1 | tr -d '\n'"
  register: unix_user_developer

- name: "Ensure group {{ developer_username }} exists"
  group:
    name: "{{ developer_username }}"
    state: present
  when: unix_user_developer.stdout != "" and unix_user_developer.stdout != developer_username

- name: "Rename user {{ unix_user_developer.stdout  }} --> {{ developer_username }}"
  command: "usermod --login {{ developer_username }} {{ unix_user_developer.stdout }}"
  when: unix_user_developer.stdout != "" and unix_user_developer.stdout != developer_username

- name: "Change user password hash"
  user:
    name: '{{ developer_username }}'
    update_password: always
    password: "{{ developer_password_hash }}"
  when: developer_password_hash != ""

- include: "{{ distro_id }}.yml"

- name: "Set developer_username to exist user"
  set_fact:
    developer_username: "{{ developer_user_info.name }}"
  when: "ansible_system == 'Linux'"

- name: "Ensure ownerships"
  command: "chown -R {{ developer_username }} '{{ developer_user_info.home }}'"
  changed_when: false
  when: "ansible_system == 'Linux' and developer_user_info.home is regex('^/home/.*')"

