---
- name: Ensure that taps are tapped.
  homebrew_tap: 
    tap: "{{ item }}"
    state: "present"
    path: "/home/linuxbrew/.linuxbrew/bin"
  with_items:
  - "digitalspacestdio/nextgen-devenv"

- name: "Ensure postgresql15"
  homebrew:
    name: "digitalspace-postgresql15"
    state: latest