---
- name: Ensure php taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items:
  - "digitalspacestdio/php"

- name: "Ensure digitalspacestdio/php/composer@2"
  homebrew:
    name: "digitalspacestdio/php/composer@2"
    state: latest

- name: "Adding 'composer@2' to 'composer_versions' array"
  set_fact:
    composer_versions: "{{ composer_versions + [ 'composer@2' ] }}"

- name: "Remove all composer versions"
  shell: "{{ homebrew_prefix }}/bin/brew list --full-name | grep 'digitalspacestdio/php/composer' && {{ homebrew_prefix }}/bin/brew uninstall --ignore-dependencies $({{ homebrew_prefix }}/bin/brew list --full-name | grep 'digitalspacestdio/php/composer') || /bin/true"
  when: "composer_versions is not defined or composer_versions | length < 1"
  tags: 
    - composerNone
