---
- name: "Enable linger"
  command: "loginctl enable-linger {{ developer_username }}"
  when: ansible_system == "Linux"

- name: "Ensure tmux"
  apt: 
    pkg: tmux
    state: present
  become: true
  when: ansible_system == "Linux"

- name: "Ensure 'set -g mouse on' in .tmux.conf"
  become: true
  become_user: "{{ developer_username }}"
  lineinfile:
    create: yes
    dest: "{{ developer_user_info.home }}/.tmux.conf"
    state: present
    regexp: 'set -g mouse'
    line: 'set -g mouse on'

- name: Create "{{ developer_username }}" systemd config dir
  become: true
  become_user: "{{ developer_username }}"
  ansible.builtin.file:
    path: "{{ developer_user_info.home }}/.config/systemd/user"
    state: directory
    mode: "0700"
  when: ansible_system == "Linux"

- name: Copy tmux systemd unit file (rootless)
  become: true
  become_user: "{{ developer_username }}"
  ansible.builtin.template:
    src: tmux.user.service
    dest: "{{ developer_user_info.home }}/.config/systemd/user/tmux.service"
    backup: 'yes'
    mode: 0600
  notify: Restart user tmux service
  when: ansible_system == "Linux"