---
# - name: Disable ipv6
#   lineinfile:
#     dest: '/etc/sysctl.conf'
#     line: '{{ item }}'
#   with_items:
#     - 'net.ipv6.conf.all.disable_ipv6 = 1'
#     - 'net.ipv6.conf.default.disable_ipv6 = 1'
#     - 'net.ipv6.conf.lo.disable_ipv6 = 1'

- name: Update apt cache
  apt: 
    update_cache: yes
  when: "ansible_system == 'Linux' and distro_id == 'debian'"

- name: Ensure debian packages
  package:
    name: "{{ debian_packages }}"
    state: present
  when: "ansible_system == 'Linux' and distro_id == 'debian'"

- name: Ensure fedora packages
  package:
    name: "{{ fedora_packages }}"
    state: present
  when: "ansible_system == 'Linux' and distro_id == 'fedora'"

- name: Ensure pip packages
  pip:
    name: "{{ pip_packages }}"
    state: present

- stat:
    path: "/etc/ssh/sshd_config"
  register: etc_ssh_sshd_config

- lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    line: 'AcceptEnv COMPOSER_AUTH'
  when: etc_ssh_sshd_config.stat.exists
