---
  - shell: "echo $({{ homebrew_prefix }}/bin/brew list | grep 'php[0-9]\\+' | /bin/true)"
    register: brew_list

  - name: "Remove all php versions"
    shell: "{{ homebrew_prefix }}/bin/brew uninstall --ignore-dependencies {{ brew_list.stdout }}"

  - name: "Remove all php versions from supervisor"
    shell: 
      cmd: "ls | grep 'php[0-9]\\+' | xargs --no-run-if-empty -I{} rm {}"
      chdir: "{{ homebrew_prefix }}/etc/digitalspace-supervisor.d"

  - name: "Remove nginx from supervisor"
    shell: 
      cmd: "ls | grep 'nginx' | xargs --no-run-if-empty -I{} rm {}"
      chdir: "{{ homebrew_prefix }}/etc/digitalspace-supervisor.d"