---
  - name: "Stat digitalspace-supervisor.d dir"
    stat:
      path: "{{ homebrew_prefix }}/etc/digitalspace-supervisor.d"
    register: stat_etc_digitalspace_supervisor_d

  - name: "Remove all php versions"
    shell: "{{ homebrew_prefix }}/bin/brew list | grep 'php[0-9]\\+' && {{ homebrew_prefix }}/bin/brew uninstall --ignore-dependencies $({{ homebrew_prefix }}/bin/brew list | grep 'php[0-9]\\+') || /bin/true"
    when: "stat_etc_digitalspace_supervisor_d.stat.exists and (php_versions is not defined or php_versions | length < 1)"

  - name: "Remove all php versions from supervisor"
    shell: 
      cmd: "ls | grep 'php[0-9]\\+' | xargs --no-run-if-empty -I{} rm {}"
      chdir: "{{ homebrew_prefix }}/etc/digitalspace-supervisor.d"
    when: "stat_etc_digitalspace_supervisor_d.stat.exists and (php_versions is not defined or php_versions | length < 1)"

  - name: "Remove nginx from supervisor"
    shell: 
      cmd: "ls | grep 'nginx' | xargs --no-run-if-empty -I{} rm {}"
      chdir: "{{ homebrew_prefix }}/etc/digitalspace-supervisor.d"
    when: "stat_etc_digitalspace_supervisor_d.stat.exists and (php_versions is not defined or php_versions | length < 1)"
